src/Entity/Musician.php
<?php

namespace App\Entity;

use App\Repository\MusicianRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MusicianRepository::class)]
class Musician extends User
{


    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'not valid !')]
    private ?string $firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image]
    private ?string $image = null;

    #[ORM\ManyToMany(targetEntity: Instrument::class, inversedBy: 'musicians')]
    private Collection $instruments;

    #[ORM\OneToMany(mappedBy: 'musician', targetEntity: Participant::class)]
    private Collection $participants;

    public function __construct()
    {
        $this->instruments = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }



    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Instrument>
     */
    public function getInstruments(): Collection
    {
        return $this->instruments;
    }

    public function addInstrument(Instrument $instrument): self
    {
        if (!$this->instruments->contains($instrument)) {
            $this->instruments->add($instrument);
        }

        return $this;
    }

    public function removeInstrument(Instrument $instrument): self
    {
        $this->instruments->removeElement($instrument);

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
            $participant->setMusician($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getMusician() === $this) {
                $participant->setMusician(null);
            }
        }

        return $this;
    }


    public function getFullname(): string
{
    return $this->getFirstName() . ' ' . $this->getLastName();
}
}

src/Controller/MusicianController.php
<?php

namespace App\Controller;

use App\Entity\Instrument;
use App\Entity\Musician;
use App\Form\InstrumentType;
use App\Form\MusicianType;
use App\Repository\MusicianRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MusicianController extends AbstractController
{
    #[Route('/musician', name: 'musician_list')]
    public function list(MusicianRepository $musicianRepository): Response
    {
        return $this->render('musician/index.html.twig', [
            'musicians' => $musicianRepository->findAll(),
        ]);
    }

    #[Route('/musician/{id}', name: 'musician_detail', requirements: ['id' => '\d+'])]
    public function detail(int $id, MusicianRepository $musicianRepository): Response
    {

        $musician = $musicianRepository->find($id);

        //si le musicien n'existe pas en BDD on retourne une erreur 404
        if ($musician === null) {
            throw $this->createNotFoundException();
        }
        return $this->render('musician/detail.html.twig', ['musician' => $musician]);
    }


    #[Route('/musician/profile', name: 'musician_profile')]
    public function new(Request $request, ManagerRegistry $doctrine): Response
    {
        $musician = $this->getUser();
        $form = $this->createForm(MusicianType::class, $musician);

        //on récupère les données du formulaire pour les mettre dans l'entité $musician
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //récupérer l'entity manager de Doctrine
            $entityManager = $doctrine->resetManager();
            //enregistrer les données en BDD
            $entityManager->persist($musician);
            $entityManager->flush();
            //rediriger l'internaute vers la page d'accueil
            return $this->redirectToRoute('homepage');
        }
        return $this->renderForm('musician/profile.html.twig', [
            'form' => $form,
        ]);

    }
}

templates/musician/_card.html.twig
<article class="card">
    <a href="{{ path('musician_detail', {'id': musician.id }) }}">
        <img src="{{ asset('uploads/' ~ musician.image) }}" alt={{"musician.fullName"}}>
    </a>
    <h3>{{ musician.fullName }}</h3>

    <ul class="badge-list">
        {% for instrument in musician.instruments %}
            <li>
                <a href="{{ path('app_instrument_show', {'id': instrument.id}) }}" class="badge badge-primary">
                    {% if instrument.icon %}
                        <i class="{{ instrument.icon }}"></i>
                    {% endif %}
                    {{ instrument.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</article>

templates/musician/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ musician.firstName }} {{ musician.lastName }}{% endblock %}

{% block body %}
    <section class="container">
    <h1>{{ musician.fullname }}</h1>
    </section>

    {{ form(form) }}

{% endblock %}

templates/musician/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MusicianController!{% endblock %}

{% block body %}

    <section class="container">
        <h1>Musicians list</h1>

        <div class="grid">

            {% for musician in musicians %}
                {# Inclure le fichier musician/_card.html.twig en envoyant la variable musician (et uniquement musician #}
                {% include 'musician/_card.html.twig' with {'musician': musician} only %}
            {% endfor %}

        </div>
    </section>



{% endblock %}

templates/musician/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MusicianController!{% endblock %}

{% block body %}

    <section class="container">
        <h1>Modify your user profile</h1>

        {# Générer la balise <form> (balise ouvrante) #}
        {{ form_start(form) }}



        {# Générer l'ensemble des champs du formulaire #}
        {{ form_widget(form) }}

        <button type="submit">Enregistrer</button>

        {# Générer la balise </form> (balise fermante) #}
        {{ form_end(form) }}

    </section>
{% endblock %}